spring.application.name=CreditCardProcessorMicroservice

server.port=8084

spring.datasource.url=jdbc:mysql://VFT4rFzWYVf66kW.root:Qnd9IGUeKMgVFU0T@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always