spring.application.name=DepositMicroservice

server.port=0
spring.datasource.url=jdbc:mysql://VFT4rFzWYVf66kW.root:Qnd9IGUeKMgVFU0T@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test

spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.consumer.group-id=amount-deposit-event
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.core.event
spring.kafka.consumer.isolation-level=READ_COMMITTED