spring.application.name=ProductsMicroservice

#KAFKA
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Datasource configuration
spring.datasource.url=jdbc:mysql://VFT4rFzWYVf66kW.root:Qnd9IGUeKMgVFU0T@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always